/* ==========================================
   UNIGUARD REPORTS & ANALYTICS MODULE
   ========================================== */

// Sample Data: Department Reports sent by OIC Officers to CSO
let departmentReportsData = [
    {
        id: "REP-2026-088",
        title: "December Month Dep Report",
        dept: "UCSC",
        oicName: "Perera",
        date: "2026-07-01",
        status: "Received",
        summary: "Submitted by Perera: Comprehensive breakdown of security incidents, shift logs, and patrol coverage across UCSC during December."
    },
    {
        id: "REP-2026-081",
        title: "UCSC Sector Patrol Coverage Log",
        dept: "UCSC Sector",
        oicName: "Perera",
        date: "2026-06-28",
        status: "Reviewed",
        summary: "Submitted by Perera: Detailed check-in timestamps and patrol coverage routes executed by JSO personnel."
    },
    {
        id: "REP-2026-075",
        title: "Annual Gate Access & Visitor Audit",
        dept: "Main Entrance",
        oicName: "Fernando",
        date: "2026-06-15",
        status: "Received",
        summary: "Submitted by Fernando: Visitor count trends, vehicle logging accuracy, and security checkpoint compliance review."
    }
];

// Sample Data: Summary Reports generated by CSO and sent to University Administrator
let summaryReportsData = [
    {
        id: "SUM-2026-012",
        title: "Mid-Year Campus Security Executive Summary",
        recipient: "University Administrator",
        date: "2026-07-15",
        status: "Sent to Admin",
        summary: "Consolidated summary compiled by CSO from all OIC department reports for H1 2026. Includes incident resolution rates, risk analysis, and personnel deployment stats."
    },
    {
        id: "SUM-2026-009",
        title: "Q1 Infrastructure & Incident Summary",
        recipient: "University Administrator",
        date: "2026-04-02",
        status: "Reviewed by Admin",
        summary: "Quarterly summary submitted to University Administrator aggregating gate security logs, critical incident reports, and JSO attendance across all departments."
    }
];

// Initialize DOM Events on Load
document.addEventListener("DOMContentLoaded", () => {
    renderReportsTable();
    renderSummaryTable();
    updateMetrics();
    startLiveClock();
});

/* ==========================================
   RENDER & METRICS MANAGEMENT
   ========================================== */
function renderReportsTable() {
    const tableBody = document.getElementById("reports-table-body");
    if (!tableBody) return;

    tableBody.innerHTML = "";

    departmentReportsData.forEach((report) => {
        const row = document.createElement("tr");

        let statusBadgeClass = "severity-low";
        let iconClass = "fa-circle-dot";

        const normalizedStatus = (report.status || "Received").toLowerCase();

        if (normalizedStatus === "reviewed" || normalizedStatus === "approved") {
            statusBadgeClass = "severity-medium";
            iconClass = "fa-circle-check";
        } else if (normalizedStatus === "pending") {
            statusBadgeClass = "severity-high";
            iconClass = "fa-clock";
        }

        row.innerHTML = `
      <td>
        <strong>#${report.id}</strong><br>
        <small style="color: var(--text-muted);">${report.title}</small>
      </td>
      <td>${report.dept}</td>
      <td>${report.oicName}</td>
      <td>${report.date}</td>
      <td><span class="sev-badge ${statusBadgeClass}"><i class="fa-solid ${iconClass}"></i> ${report.status}</span></td>
      <td class="text-right">
        <div class="action-btns">
          <button class="btn-icon" title="View Report" onclick="viewReport('${report.id}', 'dept')"><i class="fa-solid fa-eye"></i></button>
          <button class="btn-icon" title="Download File" onclick="downloadReport('${report.id}')"><i class="fa-solid fa-download"></i></button>
        </div>
      </td>
    `;
        tableBody.appendChild(row);
    });
}

function renderSummaryTable() {
    const tableBody = document.getElementById("summary-table-body");
    if (!tableBody) return;

    tableBody.innerHTML = "";

    summaryReportsData.forEach((summary) => {
        const row = document.createElement("tr");

        let statusBadgeClass = "severity-medium";
        let iconClass = "fa-paper-plane";

        const normalizedStatus = (summary.status || "Sent to Admin").toLowerCase();

        if (normalizedStatus.includes("reviewed") || normalizedStatus.includes("approved")) {
            statusBadgeClass = "severity-low";
            iconClass = "fa-circle-check";
        }

        row.innerHTML = `
      <td>
        <strong>#${summary.id}</strong><br>
        <small style="color: var(--text-muted);">${summary.title}</small>
      </td>
      <td>${summary.recipient}</td>
      <td>${summary.date}</td>
      <td><span class="sev-badge ${statusBadgeClass}"><i class="fa-solid ${iconClass}"></i> ${summary.status}</span></td>
      <td class="text-right">
        <div class="action-btns">
          <button class="btn-icon" title="View Summary" onclick="viewReport('${summary.id}', 'summary')"><i class="fa-solid fa-eye"></i></button>
          <button class="btn-icon" title="Download File" onclick="downloadReport('${summary.id}')"><i class="fa-solid fa-download"></i></button>
        </div>
      </td>
    `;
        tableBody.appendChild(row);
    });
}

function updateMetrics() {
    const totalCount = document.getElementById("total-reports-count");
    if (totalCount) totalCount.textContent = departmentReportsData.length;

    const summaryCount = document.getElementById("summary-reports-count");
    if (summaryCount) summaryCount.textContent = summaryReportsData.length;
}

/* ==========================================
   MODAL CONTROLS & GENERATE SUMMARY REPORT
   ========================================== */
function openGenerateModal() {
    const form = document.getElementById("generateReportForm");
    if (form) form.reset();

    const today = new Date().toISOString().split('T')[0];
    const lastMonth = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

    const startDateInput = document.getElementById("report-start-date");
    const endDateInput = document.getElementById("report-end-date");

    if (startDateInput) startDateInput.value = lastMonth;
    if (endDateInput) endDateInput.value = today;

    const modal = document.getElementById("generateReportModal");
    if (modal) modal.classList.add("active");
}

function closeModal(modalId) {
    const modal = document.getElementById(modalId);
    if (modal) modal.classList.remove("active");
}

function handleGenerateSummaryReport(event) {
    event.preventDefault();

    const title = document.getElementById("report-title").value;
    const notes = document.getElementById("report-notes").value;

    const newId = `SUM-2026-${Math.floor(100 + Math.random() * 900)}`;
    const today = new Date().toISOString().split('T')[0];

    const newSummaryReport = {
        id: newId,
        title: title,
        recipient: "University Administrator",
        date: today,
        status: "Sent to Admin",
        summary: notes
    };

    summaryReportsData.unshift(newSummaryReport);
    renderSummaryTable();
    updateMetrics();
    closeModal("generateReportModal");

    alert(`Summary Report #${newId} compiled and sent to University Administrator successfully!`);
}

/* ==========================================
   VIEW & DOWNLOAD ACTIONS
   ========================================== */
function viewReport(reportId, type = 'dept') {
    let report = null;

    if (type === 'summary') {
        report = summaryReportsData.find((r) => r.id === reportId);
    } else {
        report = departmentReportsData.find((r) => r.id === reportId);
    }

    if (!report) return;

    const titleEl = document.getElementById("viewReportTitle");
    const idEl = document.getElementById("view-report-id");
    const summaryEl = document.getElementById("view-report-summary");

    if (titleEl) titleEl.textContent = report.title;
    if (idEl) idEl.value = `#${report.id} [${report.status}]`;
    if (summaryEl) summaryEl.value = report.summary;

    const modal = document.getElementById("viewReportModal");
    if (modal) modal.classList.add("active");
}

function downloadReport(reportId) {
    alert(`Downloading report #${reportId}...`);
}

/* ==========================================
   SEARCH / FILTER FUNCTIONALITY
   ========================================== */
function filterReportTable() {
    filterTableGeneric("report-search-input", "reports-table");
}

function filterSummaryTable() {
    filterTableGeneric("summary-search-input", "summary-table");
}

function filterTableGeneric(inputId, tableId) {
    const inputEl = document.getElementById(inputId);
    if (!inputEl) return;

    const input = inputEl.value.toUpperCase();
    const table = document.getElementById(tableId);
    if (!table) return;

    const tr = table.getElementsByTagName("tr");

    for (let i = 1; i < tr.length; i++) {
        const td = tr[i].getElementsByTagName("td");
        let match = false;
        for (let j = 0; j < td.length; j++) {
            if (td[j]) {
                const textValue = td[j].textContent || td[j].innerText;
                if (textValue.toUpperCase().indexOf(input) > -1) {
                    match = true;
                    break;
                }
            }
        }
        tr[i].style.display = match ? "" : "none";
    }
}

/* ==========================================
   LIVE TOPBAR CLOCK
   ========================================== */
function startLiveClock() {
  initOfficerStatus();
    updateGreeting();
    function updateClock() {
    updateGreeting();
        const now = new Date();

        const timeOptions = { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true };
        const timeString = now.toLocaleTimeString('en-US', timeOptions);

        const day = String(now.getDate()).padStart(2, '0');
        const month = now.toLocaleString('en-US', { month: 'short' }).toUpperCase();
        const year = now.getFullYear();
        const dateString = `${day} ${month} ${year}`;

        const timeEl = document.getElementById("current-time");
        const dateEl = document.getElementById("current-date");

        if (timeEl) timeEl.textContent = timeString;
        if (dateEl) dateEl.textContent = dateString;
    }

    updateClock();
    setInterval(updateClock, 1000);
}
document.querySelector('.sidebar-footer .btn-logout').addEventListener('click', function() {
    // Clear session storage or tokens here if needed
    // localStorage.removeItem('token');
    
    window.location.href = '../loginPage.html';
});


document.querySelector('.sidebar-footer .btn-logout').addEventListener('click', function() {
    // Clear session storage or tokens here if needed
    // localStorage.removeItem('token');
    
    window.location.href = '../loginPage.html';
});

function updateGreeting() {
  const elements = document.querySelectorAll(".welcome-hi");
  if (!elements.length) return;
  const hour = new Date().getHours();
  let greetingText = "Good morning";
  if (hour >= 12 && hour < 17) {
    greetingText = "Good afternoon";
  } else if (hour >= 17) {
    greetingText = "Good evening";
  }
  elements.forEach((el) => {
    const text = el.textContent || "";
    const hasComma = text.trim().endsWith(",");
    el.textContent = greetingText + (hasComma ? "," : "");
  });
}

(function() { if (document.readyState === "loading") { document.addEventListener("DOMContentLoaded", updateGreeting); } else { updateGreeting(); } })();



(function injectStatusStyle() {
  if (document.getElementById("ug-status-style")) return;
  const style = document.createElement("style");
  style.id = "ug-status-style";
  style.textContent = `
    .welcome-greet { display: flex !important; align-items: center !important; gap: 0.6rem !important; flex-wrap: wrap !important; }
    .officer-status-picker { display: inline-flex !important; align-items: center !important; gap: 6px !important; background: #ffffff !important; border: 1px solid #cbd5e1 !important; border-radius: 20px !important; padding: 3px 10px !important; margin-left: 6px !important; font-size: 0.78rem !important; font-weight: 600 !important; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.06) !important; transition: all 0.2s ease !important; cursor: pointer !important; }
    .officer-status-picker:hover { border-color: #0088ff !important; box-shadow: 0 2px 5px rgba(0, 136, 255, 0.15) !important; }
    .status-indicator-dot { width: 9px !important; height: 9px !important; border-radius: 50% !important; display: inline-block !important; flex-shrink: 0 !important; transition: background-color 0.25s ease, box-shadow 0.25s ease !important; }
    .status-indicator-dot.active { background-color: #10b981 !important; box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.25) !important; }
    .status-indicator-dot.leave { background-color: #f59e0b !important; box-shadow: 0 0 0 3px rgba(245, 158, 11, 0.25) !important; }
    .status-select { border: none !important; background: transparent !important; font-size: 0.78rem !important; font-weight: 700 !important; color: #1e293b !important; cursor: pointer !important; outline: none !important; font-family: inherit !important; padding-right: 2px !important; }
    .status-select option { font-weight: 600 !important; color: #1e293b !important; background: #ffffff !important; }
  `;
  document.head.appendChild(style);
})();

function initOfficerStatus() {
  const greetContainer = document.querySelector(".welcome-greet");
  if (!greetContainer) return;

  let picker = greetContainer.querySelector("[data-status-picker]");
  if (!picker) {
    picker = document.createElement("div");
    picker.className = "officer-status-picker";
    picker.setAttribute("data-status-picker", "");
    picker.innerHTML = `
      <span class="status-indicator-dot active" data-status-dot></span>
      <select class="status-select" data-status-select title="Change your active status">
        <option value="On Active">On Active</option>
        <option value="On Leave">On Leave</option>
      </select>
    `;
    greetContainer.appendChild(picker);
  }

  const select = picker.querySelector("[data-status-select]");
  const dot = picker.querySelector("[data-status-dot]");
  if (!select || !dot) return;

  let roleKey = "uniguard_officer_status";
  const pathStr = window.location.pathname.toLowerCase();
  if (pathStr.includes("/cso/")) roleKey = "uniguard_status_CSO";
  else if (pathStr.includes("/oic/")) roleKey = "uniguard_status_OIC";
  else if (pathStr.includes("/jso/")) roleKey = "uniguard_status_JSO";

  const savedStatus = localStorage.getItem(roleKey) || localStorage.getItem("uniguard_officer_status") || "On Active";
  select.value = savedStatus;
  updateDotClass(savedStatus);

  function updateDotClass(val) {
    if (val === "On Leave") {
      dot.className = "status-indicator-dot leave";
    } else {
      dot.className = "status-indicator-dot active";
    }
  }

  select.onchange = function () {
    const val = select.value;
    localStorage.setItem(roleKey, val);
    localStorage.setItem("uniguard_officer_status", val);
    updateDotClass(val);
  };
}

(function() { if (document.readyState === "loading") { document.addEventListener("DOMContentLoaded", initOfficerStatus); } else { initOfficerStatus(); } })();
